import SwiftUI

struct Lang{
    static let dict: Dictionary<String,Dictionary<String,String>> = [
        "en":[
            "your.teams":"Your teams",
            "team.delete.message":"Deleting a team will erase all the data",
            "team.delete.title":"Delete team",
            "scout.delete.title":"Delete scouting",
            "scout.delete.message":"Deleting a scouting will erase all the data",
            "matches":"Matches",
            "training":"Training",
            "team.stats":"Team stats",
            "exercises":"Exercises",
            "stats.general":"General stats",
            "rotations.best":"Best rotations",
            "data.import":"Import data",
            "data.export":"Export data",
            "language":"Language",
            "players":"Players",
            "block":"block",
            "serve":"serve",
            "set":"set",
            "dig":"dig",
            "attack":"attack",
            "receive":"receive",
            "side.out":"Side out",
            "break.point":"Break point",
            "free.capture":"Free capture",
            "quick.anotation":"Quick anotation",
            "free.capture.description":"Match stats capture layout, but with unlimited players and no constraints by points or servers",
            "quick.anotation.description":"Workspace to take quick notes on errors made by players",
            "match.vs":"Match vs",
            "match.stats":"Match stats",
            "export.stats":"Export stats",
            "match.delete":"Delete match",
            "match.delete.description":"Deleting a match will erase all its data",
            "edit.match":"Edit match",
            "stats":"Stats",
            "player.delete":"Delete player",
            "player.delete.description":"You can later restore the player in the creation screen",
            "player.add":"Add player",
            "team.data":"Team data",
            "name":"Name",
            "organization":"Organization",
            "category":"Category",
            "gender":"Gender",
            "male":"Male",
            "female":"Female",
            "save":"Save",
            "pick.one":"Pick one",
            "number":"Number",
            "player.restore":"Restore a player",
            "player.new":"New player",
            "restore":"Restore",
            "restore.description":"You are restoring a player. Sure?",
            "cancel":"Cancel",
            "exercise.edit":"Edit exercise",
            "exercise.delete":"Delete exercise",
            "action.not.undo":"You cannot undo this action",
            "opponent":"Opponent",
            "location.court":"Location / Court",
            "home.away":"Home / Away",
            "home":"Home",
            "away":"Away",
            "date":"Date",
            "less.player.required":"This team has less players than required for the lineup",
            "number.players":"Number of players in lineup",
            "number.sets":"Number of sets",
            "match.settings":"Match settings",
            "error":"Error",
            "liberos.activate":"Activate liberos",
            "rotation":"Rotation",
            "us":"Us",
            "them":"Them",
            "first.serve":"First serve",
            "setup":"Setup",
            "all":"All",
            "description":"Description",
            "area":"Area",
            "capture.type":"Capture type",
            "count":"Count",
            "stats.like":"Stats like",
            "quick.note":"Quick note",
            "exercise.new":"New exercise",
            "spanish":"Spanish",
            "english":"English",
            "areas.to.improve":"Areas to improve",
            "set.stats":"Set stats",
            "rotation.analysis":"Rotations analysis",
            "point.log":"Point log",
            "show.finals":"Show only final stats",
            "stage":"Stage",
            "server":"Server",
            "player":"Player",
            "action":"Action",
            "action.type":"Action type",
            "point.to":"Point to",
            "score":"Score",
            "time.out.by":"Time out by ",
            "change.player":"Change player",
            "score.adjust":"Adjustment in score",
            "their.player":"Their player",
            "none":"None",
            "quick.note.title":"Capture training quick notes",
            "clear":"Clear",
            "undo":"Undo",
            "enter":"Enter",
            "areas":"Areas",
            "comments":"Comments",
            "area.not.selected":"No area selected yet",
            "capture.training":"Capture training stats",
            "capture":"Capture",
            "train.stats":"Training stats",
            "stats.date":"Date of stats",
            "day":"Day",
            "month":"Month",
            "apply":"Apply",
            "stats.by.area":"Stats by area",
            "month.bests":"This month bests",
            "time.out":"Time out",
            "select.player":"Select a player first",
            "to":"To",
            "current.lineup":"Current lineup",
            "pick.change":"Pick player in",
            "modify.rotation":"Modify the rotation",
            "rotate":"Rotate",
            "detail.title":"Add detail to the error",
            "net":"Net",
            "blocked":"Blocked",
            "out":"Out",
            "not.specify":"Not specify",
            "adjust.score":"Adjust score and server",
            "anotate.time.out":"Annotate a Time Out",
            "start":"Start",
            "actions":"Actions",
            "block.in.play":"Block in play",
            "overpass.in.play":"Over pass in play",
            "hit.in.play":"Hit in play",
            "downhit.in.play":"Down ball hit in play",
            "ace":"Ace",
            "spike":"Spike",
            "tip":"Tip",
            "dump":"Dump",
            "downhit":"Down ball hit",
//            "down ball hit":"Down ball hit",
            "whose.ball":"Whose ball?",
            "ball.handling":"Ball handling",
            "under":"Under",
            "over.the.net":"Over the net",
            "foot":"Foot fault",
            "out.rotation":"Out of rotation",
            "backrow.attack":"Back row attack",
            "match":"Match",
            "fault":"Fault",
            "earn":"Earn",
            "in.play":"In play",
            "kill.percentage":"Kill percentage",
            "serves.per.point":"Serves per point",
            "receives.per.point":"Receives per point",
            "serve.errors":"Serve errors",
            "their.errors":"Their errors",
            "receive.rating":"Receive rating",
            "last.month.stats":"Show last month stats",
            "scouting":"Scouting",
            "teams.analyzed":"Teams analyzed",
            "scout.new":"New scouting",
            "show.stats": "Show stats",
            "useful.info":"Relevant information",
            "best.attack":"Best kill",
            "worst.attack":"Worst kill",
            "best.serve":"Best server",
            "best.block":"Best blocker",
            "best.receiver":"Best passer",
            "worst.receiver":"Worst passer",
            "total.points":"Total points",
            "best.rotation.stats":"Best rotation",
            "general.trends":"General trends",
            "initial.rotation":"Starting rotation",
            "write.a.comment.max.55":"Write a comment (max 55 chars.)",
            "delete":"Delete",
            "select":"Select",
            "done":"Done",
            "over.pass.in.play":"Over pass in play",
            "attempts":"Attempts",
            "errors":"Errors",
            "earned":"Earned",
            "scouting.report":"Scouting report",
            "team.report":"Team report",
            "report":"Report",
            "date.range":"Date range",
            "number.matches":"Number of matches",
            "number.trainings":"Number of trainings",
            "match.report":"Match report",
            "result":"Result",
            "totals":"Totals",
            "match.bests":"Match bests",
            "mark":"Mark",
            "multi.match.report":"Multi match report",
            "matches.report":"Matches report",
            "league":"League",
            "non.league":"Non league",
            "tournament":"Tournament",
            "empty.tournaments":"No torunaments created",
            "no.tournament":"No tournament",
            "league.matches":"League matches",
            "tournaments":"Tournaments",
            "tournament.delete":"Delete tournament",
            "tournament.delete.description":"The matches asociated with the tournament won't be deleted",
            "general":"General",
            "tournament.new":"New tournament",
            "tournament.setup":"Tournament settings",
            "end.date":"End date",
            "start.date":"Start date",
            "location":"Location",
            "all.matches":"All matches",
            "birthday":"Birthday",
            "block.out":"Block out",
            "report.type":"Report type",
            "general.report":"General report",
            "full.report":"Full report",
            "tournament.stats":"Tournament stats",
            "players.rank.by.area":"Players rank by area",
            "team":"Team",
            "add.from.team":"Add from other team",
            "pick.team":"Pick a team",
            "pick.player":"Pick a player",
            "add.players":"Add players",
            "serve.historical.stats":"Serve historical stats",
            "receive.historical.stats":"Receive historical stats",
            "atk.historical.stats":"Attack historical stats",
            "kills":"Kills",
            "height":"Height",
            "weight":"Weight",
            "breadth":"Breadth",
            "one.hand.reach":"One hand reach",
            "two.hand.reach":"Two hand reach",
            "attack.reach":"Attack reach",
            "block.reach":"Block reach",
            "attack.jump":"Attack jump",
            "block.jump":"Block jump",
            "player.data":"Player data",
            "player.measures":"Player measurements",
            "coming.soon":"Coming soon..."
        ],
        "es":[
            "your.teams":"Tus equipos",
            "team.delete.message":"Eliminar un equipo borra todos sus datos",
            "team.delete.title":"Eliminar equipo",
            "scout.delete.title":"Eliminar scouting",
            "scout.delete.message":"Eliminar un scouting elimina todos los datos",
            "matches":"Partidos",
            "training":"Entrenamiento",
            "team.stats":"Estadisticas",
            "exercises":"Ejercicios",
            "stats.general":"Estadísticas generales",
            "rotations.best":"Mejores rotaciones",
            "data.import":"Importar datos",
            "data.export":"Exportar datos",
            "language":"Idioma",
            "players":"Jugadores",
            "block":"bloqueo",
            "serve":"saque",
            "set":"colocacion",
            "dig":"defensa",
            "attack":"ataque",
            "receive":"recepcion",
            "side.out":"Side out",
            "break.point":"Break point",
            "free.capture":"Estadisticas libres",
            "quick.anotation":"Anotaciones rápidas",
            "free.capture.description":"Estructura similar a la captura de estadisticas de partido pero con jugadores ilimitados y sin restricciones de puntos o sacadores",
            "quick.anotation.description":"Area de captura de anotaciones sobre los errores cometidos por los jugadores",
            "match.vs":"Partido contra",
            "match.stats":"Estadisticas del partido",
            "export.stats":"Exportar estadisticas",
            "match.delete":"Eliminar partido",
            "match.delete.description":"Eliminar un partido borra todos sus datos",
            "edit.match":"Editar partido",
            "stats":"Estadisticas",
            "player.delete":"Eliminar jugador",
            "player.delete.description":"Más tarde podras restaurar este jugador desde la pestaña de nuevo jugador",
            "player.add":"Añadir jugador",
            "team.data":"Datos del equipo",
            "name":"Nombre",
            "organization":"Organización",
            "category":"Categoría",
            "gender":"Género",
            "male":"Masculino",
            "female":"Femenino",
            "save":"Guardar",
            "pick.one":"Seleccionar",
            "number":"Número",
            "player.restore":"Restaurar un jugador",
            "player.new":"Nuevo jugador",
            "restore":"Restaurar",
            "restore.description":"Estas restaurando un jugador. Desea continuar?",
            "cancel":"Cancelar",
            "exercise.edit":"Editar ejercicio",
            "exercise.delete":"Eliminar ejercicio",
            "action.not.undo":"No se puede deshacer esta acción",
            "opponent":"Contrincante",
            "location.court":"Lugar / Pista",
            "home.away":"Local / Visitante",
            "home":"Local",
            "away":"Visitante",
            "date":"Fecha",
            "less.player.required":"Este equipo tiene menos jugadores de los necesarios para la rotación",
            "number.players":"Número de jugadores",
            "number.sets":"Número de sets",
            "match.settings":"Ajustes del partido",
            "error":"Error",
            "liberos.activate":"Activar liberos",
            "rotation":"Rotación",
            "us":"Nosotros",
            "them":"Ellos",
            "first.serve":"Primer saque",
            "setup":"Configurar",
            "all":"Todas",
            "description":"Descripción",
            "area":"Área",
            "capture.type":"Tipo de captura",
            "count":"Conteo",
            "stats.like":"Estadísticas",
            "quick.note":"Anotacion rápida",
            "exercise.new":"Nuevo ejercicio",
            "spanish":"Español",
            "english":"Inglés",
            "areas.to.improve":"Areas a mejorar",
            "set.stats":"Estadísticas del set",
            "rotation.analysis":"Analisis de las rotaciones",
            "point.log":"Registro de puntos",
            "show.finals":"Mostrar solo estadísticas finales",
            "stage":"Fase",
            "server":"Sacador",
            "player":"Jugador",
            "action":"Acción",
            "action.type":"Tipo",
            "point.to":"Punto para",
            "score":"Marcador",
            "time.out.by":"Tiempo muerto para ",
            "change.player":"Cambiar jugador",
            "score.adjust":"Ajuste en el marcador",
            "their.player":"Su jugador",
            "none":"Nadie",
            "quick.note.title":"Capturar notas rápidas",
            "clear":"Limpiar",
            "undo":"Deshacer",
            "enter":"Guardar",
            "areas":"Áreas",
            "comments":"Comentarios",
            "area.not.selected":"No hay área seleccionada",
            "capture.training":"Capturar estadísticas de entrenamiento",
            "capture":"Capturar",
            "train.stats":"Estadísticas de entrenamiento",
            "stats.date":"Fecha de las estadísticas",
            "day":"Dia",
            "month":"Mes",
            "apply":"Aplicar",
            "stats.by.area":"Estadísticas por área",
            "month.bests":"Los mejores del mes",
            "time.out":"Tiempo muerto",
            "select.player":"Selecciona un jugador primero",
            "to":"Para",
            "current.lineup":"Alineación actual",
            "pick.change":"Selecciona al cambio",
            "modify.rotation":"Modificar la rotación",
            "rotate":"Rotar",
            "detail.title":"Añade un detalle al error",
            "net":"Red",
            "blocked":"Bloqueado",
            "out":"Fuera",
            "not.specify":"Sin especificar",
            "adjust.score":"Ajustar marcador y sacador",
            "anotate.time.out":"Anotar un tiempo muerto",
//            "start":"Empezar",
            "actions":"Acciones",
            "block.in.play":"Bloqueo en juego",
            "overpass.in.play":"Recepción pasada en juego",
            "hit.in.play":"Ataque en juego",
            "downhit.in.play":"Pase fácil en juego",
            "ace":"Saque directo",
            "spike":"Remate",
            "tip":"Finta",
            "dump":"Finta del colocador",
            "downhit":"Pase fácil",
            "whose.ball":"De quien era?",
            "ball.handling":"Dobles / Acompañamiento",
            "under":"Invasión",
            "over.the.net":"Invasión aérea",
            "foot":"Línea en el saque",
            "out.rotation":"Falta de rotación",
            "backrow.attack":"Zaguero",
            "match":"Partido",
            "fault":"Falta",
            "earn":"Ganado",
            "in.play":"En juego",
            "kill.percentage":"Puntos en ataque",
            "serves.per.point":"Saques para puntuar",
            "receives.per.point":"Recepciones para puntuar",
            "serve.errors":"Errores de saque",
            "their.errors":"Errores del contrario",
            "kills":"Puntos",
            "blocks":"Bloqueos",
            "aces":"Directos",
            "receive.rating":"Nota de recepcion",
            "last.month.stats":"Mostrar estadisticas del ultimo mes",
            "scouting":"Scouting",
            "teams.analyzed":"Equipos analizados",
            "scout.new":"Nuevo análisis",
            "show.stats": "Mostrar datos",
            "useful.info":"Información relevante",
            "best.attack":"Mejor ataque",
            "worst.attack":"Peor ataque",
            "best.serve":"Mejor saque",
            "best.block":"Mejor bloqueo",
            "best.receiver":"Mejor rece",
            "worst.receiver":"Peor rece",
            "total.points":"Puntos totales",
            "best.rotation.stats":"Mejor rotación",
            "general.trends":"Tendencias generales",
            "initial.rotation":"Rotación inicial",
            "write.a.comment.max.55":"Escribe un comentario (max 55 car.)",
            "delete":"Borrar",
            "select":"Seleccionar",
            "done":"Listo",
            "over.pass.in.play":"Recepcion pasada en juego",
            "attempts":"Pases totales",
            "errors":"Errores",
            "earned":"Puntos ganados",
            "scouting.report":"Informe scouting",
            "team.report":"Informe de equipo",
            "report":"Informe",
            "date.range":"Rango de fechas",
            "number.matches":"Nº de partidos",
            "number.trainings":"Nº de entrenamientos",
            "match.report":"Informe de partido",
            "result":"Resultado",
            "totals":"Totales",
            "match.bests":"Mejores del partido",
            "mark":"Nota",
            "multi.match.report":"Informe multiples partidos",
            "matches.report":"Informe partidos",
            "league":"Liga",
            "non.league":"Fuera de liga",
            "tournament":"Torneo",
            "empty.tournaments":"No existen torneos",
            "no.tournament":"Sin torneo",
            "league.matches":"Partidos de liga",
            "tournaments":"Torneos",
            "tournament.delete":"Borrar torneo",
            "tournament.delete.description":"Los partidos asociados con el torneo no se eliminaran",
            "general":"General",
            "tournament.new":"Nuevo torneo",
            "tournament.setup":"Ajustes del torneo",
            "end.date":"Fecha de fin",
            "start.date":"Fecha de inicio",
            "location":"Lugar",
            "all.matches":"Todos los partidos",
            "birthday":"Fecha de nacimiento",
            "block.out":"Block out",
            "report.type":"Tipo de informe",
            "general.report":"Informe general",
            "full.report":"Informe completo",
            "tournament.stats":"Estadisticas del torneo",
            "players.rank.by.area":"Ranking de jugadores por area",
            "team":"Equipo",
            "add.from.team":"Añadir de otro equipo",
            "pick.team":"Elegir equipo",
            "pick.player":"Elegir jugador",
            "add.players":"Añadir jugadores",
            "serve.historical.stats":"Estadísticas históricas de saque",
            "receive.historical.stats":"Estadísticas históricas de recepción",
            "atk.historical.stats":"Estadísticas históricas de ataque",
            "height":"Altura",
            "weight":"Peso",
            "breadth":"Envergadura",
            "one.hand.reach":"Alcance una mano",
            "two.hand.reach":"Alcance dos manos",
            "attack.reach":"Alcance en ataque",
            "block.reach":"Alcance en bloqueo",
            "attack.jump":"Salto en ataque",
            "block.jump":"Salto en bloqueo",
            "player.data":"Datos del jugador",
            "player.measures":"Medidas del jugadors",
            "coming.soon":"Proximamente..."
        ]
    ]
}
