import SwiftUI

struct Lang{
    static let dict: Dictionary<String,Dictionary<String,String>> = [
        "en":[
            "your.teams":"Your teams",
            "team.delete.message":"Deleting a team will erase all the data",
            "team.delete.title":"Delete team",
            "scout.delete.title":"Delete scouting",
            "scout.delete.message":"Deleting a scouting will erase all the data",
            "matches":"Matches",
            "training":"Training",
            "team.stats":"Team stats",
            "exercises":"Exercises",
            "stats.general":"General stats",
            "rotations.best":"Best rotations",
            "data.import":"Import data",
            "data.export":"Export data",
            "language":"Language",
            "players":"Players",
            "block":"block",
            "serve":"serve",
            "set":"set",
            "dig":"dig",
            "attack":"attack",
            "receive":"receive",
            "side.out":"Side out (K1)",
            "break.point":"Break point (K2)",
            "free.capture":"Free capture",
            "quick.anotation":"Quick anotation",
            "free.capture.description":"Match stats capture layout, but with unlimited players and no constraints by points or servers",
            "quick.anotation.description":"Workspace to take quick notes on errors made by players",
            "match.vs":"Match vs",
            "match.stats":"Match stats",
            "export.stats":"Export stats",
            "match.delete":"Delete match",
            "match.delete.description":"Deleting a match will erase all its data",
            "edit.match":"Edit match",
            "stats":"Stats",
            "player.delete":"Delete player",
            "player.delete.description":"You can later restore the player in the creation screen",
            "player.add":"Add player",
            "team.data":"Team data",
            "name":"Name",
            "organization":"Organization",
            "category":"Category",
            "gender":"Gender",
            "male":"Male",
            "female":"Female",
            "save":"Save",
            "pick.one":"Pick one",
            "number":"Number",
            "player.restore":"Restore a player",
            "player.new":"New player",
            "restore":"Restore",
            "restore.description":"You are restoring a player. Sure?",
            "cancel":"Cancel",
            "exercise.edit":"Edit exercise",
            "exercise.delete":"Delete exercise",
            "action.not.undo":"You cannot undo this action",
            "opponent":"Opponent",
            "location.court":"Location / Court",
            "home.away":"Home / Away",
            "home":"Home",
            "away":"Away",
            "date":"Date",
            "less.player.required":"This team has less players than required for the lineup",
            "number.players":"Number of players in lineup",
            "number.sets":"Number of sets",
            "match.settings":"Match settings",
            "error":"Error",
            "liberos.activate":"Activate liberos",
            "rotation":"Rotation",
            "us":"Us",
            "them":"Them",
            "first.serve":"First serve",
            "setup":"Setup",
            "all":"All",
            "description":"Description",
            "area":"Area",
            "capture.type":"Capture type",
            "count":"Count",
            "stats.like":"Stats like",
            "quick.note":"Quick note",
            "exercise.new":"New exercise",
            "spanish":"Español",
            "english":"English",
            "areas.to.improve":"Areas to improve",
            "set.stats":"Set stats",
            "rotation.analysis":"Rotations analysis",
            "point.log":"Point log",
            "show.finals":"Show only final stats",
            "stage":"Stage",
            "server":"Server",
            "player":"Player",
            "action":"Action",
            "action.type":"Action type",
            "point.to":"Point to",
            "score":"Score",
            "time.out.by":"Time out by ",
            "change.player":"Change player",
            "score.adjust":"Adjustment in score",
            "their.player":"Their player",
            "none":"None",
            "quick.note.title":"Capture training quick notes",
            "clear":"Clear",
            "undo":"Undo",
            "enter":"Enter",
            "areas":"Areas",
            "comments":"Comments",
            "area.not.selected":"No area selected yet",
            "capture.training":"Capture training stats",
            "capture":"Capture",
            "train.stats":"Training stats",
            "stats.date":"Date of stats",
            "day":"Day",
            "month":"Month",
            "apply":"Apply",
            "stats.by.area":"Stats by area",
            "month.bests":"This month bests",
            "time.out":"Time out",
            "select.player":"Try selecting a player or capturing an action before changing a player",
            "to":"To",
            "current.lineup":"Current lineup",
            "pick.change":"Pick player in",
            "modify.rotation":"Modify the rotation",
            "rotate":"Rotate",
            "detail.title":"Add detail to the error",
            "net":"Net",
            "blocked":"Blocked",
            "out":"Out",
            "not.specify":"Not specify",
            "adjust.score":"Adjust score and server",
            "anotate.time.out":"Annotate a Time Out",
            "start":"Start",
            "actions":"Actions",
            "block.in.play":"Block in play",
            "overpass.in.play":"Over pass in play",
            "hit.in.play":"Hit in play",
            "downhit.in.play":"Down ball hit in play",
            "ace":"Ace",
            "spike":"Spike",
            "tip":"Tip",
            "dump":"Dump",
            "downhit":"Down ball hit",
//            "down ball hit":"Down ball hit",
            "whose.ball":"Whose ball?",
            "ball.handling":"Ball handling",
            "under":"Under",
            "over.the.net":"Over the net",
            "foot":"Foot fault",
            "out.rotation":"Out of rotation",
            "backrow.attack":"Back row attack",
            "match":"Match",
            "fault":"Fault",
            "earn":"Earn",
            "in.play":"In play",
            "kill.percentage":"Kill percentage",
            "serves.per.point":"Serves per point",
            "receives.per.point":"Receives per point",
            "serve.errors":"Serve errors",
            "their.errors":"Their errors",
            "receive.rating":"Receive rating",
            "last.month.stats":"Show last month stats",
            "scouting":"Scouting",
            "teams.analyzed":"Teams analyzed",
            "scout.new":"New scouting",
            "show.stats": "Show stats",
            "useful.info":"Relevant information",
            "best.attack":"Best kill",
            "worst.attack":"Worst kill",
            "best.serve":"Best server",
            "best.block":"Best blocker",
            "best.receiver":"Best passer",
            "worst.receiver":"Worst passer",
            "total.points":"Total points",
            "best.rotation.stats":"Best rotation",
            "general.trends":"General trends",
            "initial.rotation":"Starting rotation",
            "write.a.comment.max.55":"Write a comment (max 55 chars.)",
            "delete":"Delete",
            "select":"Select",
            "done":"Done",
            "over.pass.in.play":"Over pass in play",
            "attempts":"Attempts",
            "errors":"Errors",
            "earned":"Earned",
            "scouting.report":"Scouting report",
            "team.report":"Team report",
            "report":"Report",
            "date.range":"Date range",
            "number.matches":"Number of matches",
            "number.trainings":"Number of trainings",
            "match.report":"Match report",
            "result":"Result",
            "totals":"Totals",
            "match.bests":"Match bests",
            "mark":"Mark",
            "multi.match.report":"Multi match report",
            "matches.report":"Matches report",
            "league":"League",
            "non.league":"Non league",
            "tournament":"Tournament",
            "empty.tournaments":"No torunaments created",
            "no.tournament":"No tournament",
            "league.matches":"League matches",
            "tournaments":"Tournaments",
            "tournament.delete":"Delete tournament",
            "tournament.delete.description":"The matches asociated with the tournament won't be deleted",
            "general":"General",
            "tournament.new":"New tournament",
            "tournament.setup":"Tournament settings",
            "end.date":"End date",
            "start.date":"Start date",
            "location":"Location",
            "all.matches":"All matches",
            "birthday":"Birthday",
            "block.out":"Block out",
            "report.type":"Report type",
            "general.report":"General report",
            "full.report":"Full report",
            "tournament.stats":"Tournament stats",
            "players.rank.by.area":"Players rank by area",
            "team":"Team",
            "add.from.team":"Add from other team",
            "pick.team":"Pick a team",
            "pick.player":"Pick a player",
            "add.players":"Add players",
            "serve.historical.stats":"Serve historical stats",
            "receive.historical.stats":"Receive historical stats",
            "atk.historical.stats":"Attack historical stats",
            "kills":"Kills",
            "height":"Height",
            "weight":"Weight",
            "breadth":"Breadth",
            "one.hand.reach":"One hand reach",
            "two.hand.reach":"Two hand reach",
            "attack.reach":"Attack reach",
            "block.reach":"Block reach",
            "attack.jump":"Attack jump",
            "block.jump":"Block jump",
            "player.data":"Player data",
            "player.measures":"Player measurements",
            "coming.soon":"Coming soon...",
            "gp":"W-L",
            "help":"Help",
            "general.explanation":"There are three screens in here: capture, stats and point log. Each one display relevant data for the match.",
            "capture.explanation":"In this screen you are going to input match actions.",
            "the.score": "The score",
            "the.score.explanation.1":"The score starts at 0-0. A volleyball ball will appear next to the score of the team that is serving.",
            "the.score.explanation.2":"If you need to override the score or the team that is serving you simply tap any of the score buttons and a window will appear so you cand make adjustments.",
            "current.rotation":"Current rotation",
            "current.rotation.explanation.1":"The rotation will be the one you entered in the game setup screen and will automatically update as you take stats.",
            "current.rotation.explanation.2":"If you need to adjust the rotation any time, tou can tap on it and a window will appear for you to make the adjustments.",
            "capturing.stats":"Capturing stats",
            "capturing.stats.explanation.1":"1. Press the button of the player that parformed the action or if the action was from the opponent, tap the 'their player' button.",
            "capturing.stats.explanation.2":"2. Press the button of the action that the player performed.",
            "capturing.stats.explanation.3":"3. Press the enter button to save the action.",
            "capturing.stats.explanation.4":"You can undo the last action or clear the selected buttons with the dedicated buttons 'clear' and 'undo'.",
            "servers":"Servers",
            "servers.explanation.1":"Whenever is your turn to serve, a volleyball ball will appear next to the number of the player that must serve.",
            "stats.explanation.1":"In this screen is shown a summary of your team stats. The data is displayed in table format and divided into areas.",
            "stats.explanation.2":"You can find more information in the stats section.",
            "point.log.explanation":"In this screen is displayed a record of the actions annotated during the match. The columns show the following information:",
            "stage.explanation":"Shows if you are serving or receiving.",
            "server.explanation":"Shows the name of the player serving or 'their player' if the opponent is serving.",
            "player.explanation":"This is the player that performed the action.",
            "action.type.explanation":"This shows if the action is in-rally, an error, a point earned or a fault.",
            "action.explanation":"This is the name of the action. For some actions will display details between brackets.",
            "point.to.explanation":"The point is for your team ('us') or for the opponent ('them').",
            "score.explanation":"Final score after the action.",
            "actions.explanation":"There are many action buttons to provide detailed stats, but you can choose to be less specific and capture all the actions of the same topic under the same button (ex. Dig, free ball and whose ball? under dig action)",
            "in.rally.actions":"In-rally actions (gray)",
            "in.rally.explanation":"This are in game actions, so the do not end the rally after the action is annotated",
            "in.rally.dig":"A ball brought under control after an opponent's attack (Free ball not included).",
            "in.rally.free.ball.1":"A free ball that is recoverable but not settable and it's far from the 3m line.",
            "in.rally.free.ball.2":"A free ball that is high enough, near to the 3m line and set by the setter.",
            "in.rally.free.ball.3":"A free ball that is perfect, near to the right of the center allowing all the options to set.",
            "in.rally.block":"A block to an opponent's attack that they keep in play.",
            "in.rally.overpass":"A receive pass that goes over the net to the opponent's side. If the opponent makes a kill in the first touch then use receive error.",
            "in.rally.receive.1":"A receive that is recoverable but not settable and it's far from the 3m line.",
            "in.rally.receive.2":"A receive that is high enough, near to the 3m line and set by the setter.",
            "in.rally.receive.3":"A receive that is perfect, near to the right of the center allowing all the options to set.",
            "in.rally.serve.1":"A serve that leads to an opponent's 3-receive.",
            "in.rally.serve.2":"A serve that leads to an opponent's 2-receive.",
            "in.rally.serve.3":"A serve that leads to an opponent's 1-receive.",
            "in.rally.hit":"An attack by your player that is still in play.",
            "in.rally.downhit":"A down ball hit by your player that is still in play.",
            "earned.actions":"Earned actions (green)",
            "earned.actions.explanation":"This actions are points earned.",
            "earned.ace":"A serve that results in a direct point or a receive error.",
            "earned.spike":"A ball that is killed and goes direct to the froor or leads to a dig error.",
            "earned.tip":"Soft hit tipically with the finger tips that ends in a point.",
            "earned.dump":"A soft hit or a tip tipically by the setter near the net.",
            "earned.downhit":"A hit made by a player standing on the floor.",
            "earned.block":"When a player blocks a ball for a point.",
            "error.actions":"Error actions (yellow)",
            "error.actions.explanation":"Actions tht lead to a point for the opponent.",
            "error.serve":"When the ball goes out or to the net.",
            "error.attack":"When the ball goes out, to the net or is blocked.",
            "error.block":"A ball touched by the blocker that ends in a point for the offensive team.",
            "error.whose.ball":"Two or more players attemptimg to play the same ball resulting in an error.",
            "error.receive":"A serve not controlled or reached by the receiving player.",
            "error.dig":"A failed attempt to control an attacked ball (spike, tip, dump, down ball hit)",
            "error.set":"A poor set leading to an error",
            "error.free.ball":"An easy first ball receive error",
            "fault.actions":"Fault actions (red)",
            "fault.actions.explanation":"This actions are technical faults.",
            "fault.net":"A player illegally touches the net.",
            "fault.ball.handling":"A player made double contact or lift while playing the ball.",
            "fault.under":"A player crossed the center line under the net.",
            "fault.foot":"The server touched or crossed the line while serving (this counts as a serve error).",
            "fault.over.the.net":"A player touches the ball on the opponent's side over the net (this counts as a block error).",
            "fault.out.rotation":"Players overlapping or the team was not in the correct rotation.",
            "fault.backrow.attack":"A back row player attempts an attack in front of the 3m line (this counts as an attack error).",
            "stats.explanation":"There are different screens showing the same information but with input data from the whole match or from one of the sets already played divided into areas.",
            "stats.general.explanation":"Here we have some relevant information of mixed areas",
            "general.their.errors":"Number of errors made by the opponent without your team's direct action.",
            "general.serve.errors":"Number of serve errors by your team.",
            "general.receive.rating":"Average receive mark for your team (over 3)",
            "general.kill.percentage":"Percentage of attacks that ended in a point for your team. If you are not taking in-rally stats, this information could be unreal.",
            "general.match.bests":"*If you are in the match summary, here you'll also see who is the best player in each area",
            "stats.per.area":"Stats per area",
            "area.explanation":"Here the information is displayed by player and divided in the following areas:",
            "area.attack.1":"Here the data shown is the number of hits, the kills, the errors and the kill percentage.",
            "area.attack.2":"If no in-rally data is captured, the kill percentage could return unreal data.",
            "area.block":"Here are shown the total block attempts, the earned blocks and the errors.",
            "area.dig":"Here are displayed the dig attempts and the errors.",
            "area.downhit":"Here are shown the total down ball hit attempts, the earned and the errors. This data is the totals of the team.",
            "area.fault":"Here are displayed the number of faults of each type.",
            "area.free":"Here are shown the total number of free ball passes, the errors, 1-free ball (-), 2-free ball (+), 3-free ball (++) and the average mark (over 3).",
            "area.receive":"Here are shown the total number of receive passes, the errors, 1-receive (-), 2-receive (+), 3-receive (++) and the average mark (over 3).",
            "area.serve":"Here are displayed the total number of serves, the aces, the errors, 1-serve (-), 2-serve (+), 3-serve (++), the average mark (over 3) and the number of points won by your team while each player was serving.",
            "area.set":"Here are displayed the set errors.",
            "1.receive":"1-Receive",
            "2.receive":"2-Receive",
            "3.receive":"3-Receive",
            "1.serve":"1-Serve",
            "2.serve":"2-Serve",
            "3.serve":"3-Serve",
            "offline":"No internet connection",
            "stats.rotation.explanation":"Here are displayed the rotation stats. Is shown the initial rotation but the data is from every iteration of the rotation.",
            "side.out.explanation":"Sideout point are the ones that your team win while is receiving (K1). It means, the point when you get the serve again.",
            "break.point.explanation":"Break points are the ones that your team win while is serving (K2).",
            "user.area":"User area",
            "log.out":"Log out",
            "login":"Log in",
            "sign.up":"Sign up",
            "verify.password":"Repeat password",
            "password":"Password",
            "username":"User name",
            "email":"Email",
            "backup.error":"Error while doing backup",
            "backup.saved":"Backup done",
            "data.imported":"Backup restored",
            "error.importing":"Error while restoring backup",
            "show.game.graph":"Show game graph",
            "position":"Position",
            "setter":"Setter",
            "opposite":"Oppsite",
            "outside":"Outside hitter",
            "midBlock":"Middle blocker",
            "libero":"Libero",
            "universal":"Universal",
            "game.mode":"Game mode",
            "teams":"Teams",
            "same.position":"Same position",
            "other":"Other",
            "player.report":"Player report",
            "match.played":"Matches played",
            "set.played":"Sets played",
            "ace.short":"Ace",
            "generate":"Generate",
            "pick.date.range":"Pick date range",
            "add.feedback":"Add feedback",
            "customize.report":"Customize report",
            "points":"Points",
            "not.enough.setters":"You have not enough setters or are wrong placed",
            "cant.change":"Can't perform the substitution",
            "n.changes":"Changes",
            "match.compare":"Compare to previous",
            "error.tree":"Error tree",
            "actual":"Actual",
            "previous":"Previous",
            "serve.detail":"Serve detail",
            "receive.detail":"Receive detail",
            "attack.detail":"Attack detail",
            "full.stats":"Full stats",
            "stats.by.type":"Stats type",
            "fill.stats":"Fill stats",
            "last.point":"Previous point",
            "next.point":"Current point",
            "last.action":"Previous action",
            "next.action":"Next action",
            "in.game.actions":"In game actions",
            "no.action":"No registered actions",
            "no.next.point":"Use the usual capture method"
        ],
        "es":[
            "your.teams":"Tus equipos",
            "team.delete.message":"Eliminar un equipo borra todos sus datos",
            "team.delete.title":"Eliminar equipo",
            "scout.delete.title":"Eliminar scouting",
            "scout.delete.message":"Eliminar un scouting elimina todos los datos",
            "matches":"Partidos",
            "training":"Entrenamiento",
            "team.stats":"Estadisticas",
            "exercises":"Ejercicios",
            "stats.general":"Estadísticas generales",
            "rotations.best":"Mejores rotaciones",
            "data.import":"Importar datos",
            "data.export":"Exportar datos",
            "language":"Idioma",
            "players":"Jugadores",
            "block":"bloqueo",
            "serve":"saque",
            "set":"colocacion",
            "dig":"defensa",
            "attack":"ataque",
            "receive":"recepcion",
            "side.out":"Side out (K1)",
            "break.point":"Break point (K2)",
            "free.capture":"Estadisticas libres",
            "quick.anotation":"Anotaciones rápidas",
            "free.capture.description":"Estructura similar a la captura de estadisticas de partido pero con jugadores ilimitados y sin restricciones de puntos o sacadores",
            "quick.anotation.description":"Area de captura de anotaciones sobre los errores cometidos por los jugadores",
            "match.vs":"Partido contra",
            "match.stats":"Estadisticas del partido",
            "export.stats":"Exportar estadisticas",
            "match.delete":"Eliminar partido",
            "match.delete.description":"Eliminar un partido borra todos sus datos",
            "edit.match":"Editar partido",
            "stats":"Estadisticas",
            "player.delete":"Eliminar jugador",
            "player.delete.description":"Más tarde podras restaurar este jugador desde la pestaña de nuevo jugador",
            "player.add":"Añadir jugador",
            "team.data":"Datos del equipo",
            "name":"Nombre",
            "organization":"Organización",
            "category":"Categoría",
            "gender":"Género",
            "male":"Masculino",
            "female":"Femenino",
            "save":"Guardar",
            "pick.one":"Seleccionar",
            "number":"Número",
            "player.restore":"Restaurar un jugador",
            "player.new":"Nuevo jugador",
            "restore":"Restaurar",
            "restore.description":"Estas restaurando un jugador. Desea continuar?",
            "cancel":"Cancelar",
            "exercise.edit":"Editar ejercicio",
            "exercise.delete":"Eliminar ejercicio",
            "action.not.undo":"No se puede deshacer esta acción",
            "opponent":"Contrincante",
            "location.court":"Lugar / Pista",
            "home.away":"Local / Visitante",
            "home":"Local",
            "away":"Visitante",
            "date":"Fecha",
            "less.player.required":"Este equipo tiene menos jugadores de los necesarios para la rotación",
            "number.players":"Número de jugadores",
            "number.sets":"Número de sets",
            "match.settings":"Ajustes del partido",
            "error":"Error",
            "liberos.activate":"Activar liberos",
            "rotation":"Rotación",
            "us":"Nosotros",
            "them":"Ellos",
            "first.serve":"Primer saque",
            "setup":"Configurar",
            "all":"Todas",
            "description":"Descripción",
            "area":"Área",
            "capture.type":"Tipo de captura",
            "count":"Conteo",
            "stats.like":"Estadísticas",
            "quick.note":"Anotacion rápida",
            "exercise.new":"Nuevo ejercicio",
            "spanish":"Español",
            "english":"English",
            "areas.to.improve":"Areas a mejorar",
            "set.stats":"Estadísticas del set",
            "rotation.analysis":"Analisis de las rotaciones",
            "point.log":"Registro de puntos",
            "show.finals":"Mostrar solo estadísticas finales",
            "stage":"Fase",
            "server":"Sacador",
            "player":"Jugador",
            "action":"Acción",
            "action.type":"Tipo",
            "point.to":"Punto para",
            "score":"Marcador",
            "time.out.by":"Tiempo muerto para ",
            "change.player":"Cambiar jugador",
            "score.adjust":"Ajuste en el marcador",
            "their.player":"Su jugador",
            "none":"Nadie",
            "quick.note.title":"Capturar notas rápidas",
            "clear":"Limpiar",
            "undo":"Deshacer",
            "enter":"Guardar",
            "areas":"Áreas",
            "comments":"Comentarios",
            "area.not.selected":"No hay área seleccionada",
            "capture.training":"Capturar estadísticas de entrenamiento",
            "capture":"Capturar",
            "train.stats":"Estadísticas de entrenamiento",
            "stats.date":"Fecha de las estadísticas",
            "day":"Dia",
            "month":"Mes",
            "apply":"Aplicar",
            "stats.by.area":"Estadísticas por área",
            "month.bests":"Los mejores del mes",
            "time.out":"Tiempo muerto",
            "select.player":"Selecciona un jugador primero o captura una acción antes de cambiar a un jugador.",
            "to":"Para",
            "current.lineup":"Alineación actual",
            "pick.change":"Selecciona al cambio",
            "modify.rotation":"Modificar la rotación",
            "rotate":"Rotar",
            "detail.title":"Añade un detalle al error",
            "net":"Red",
            "blocked":"Bloqueado",
            "out":"Fuera",
            "not.specify":"Sin especificar",
            "adjust.score":"Ajustar marcador y sacador",
            "anotate.time.out":"Anotar un tiempo muerto",
//            "start":"Empezar",
            "actions":"Acciones",
            "block.in.play":"Bloqueo en juego",
            "overpass.in.play":"Recepción pasada en juego",
            "hit.in.play":"Ataque en juego",
            "downhit.in.play":"Pase fácil en juego",
            "ace":"Saque directo",
            "spike":"Remate",
            "tip":"Finta",
            "dump":"Finta del colocador",
            "downhit":"Pase fácil",
            "whose.ball":"De quien era?",
            "ball.handling":"Dobles / Acompañamiento",
            "under":"Invasión",
            "over.the.net":"Invasión aérea",
            "foot":"Línea en el saque",
            "out.rotation":"Falta de rotación",
            "backrow.attack":"Zaguero",
            "match":"Partido",
            "fault":"Falta",
            "earn":"Ganado",
            "in.play":"En juego",
            "kill.percentage":"Puntos en ataque",
            "serves.per.point":"Saques para puntuar",
            "receives.per.point":"Recepciones para puntuar",
            "serve.errors":"Errores de saque",
            "their.errors":"Errores contrario",
            "kills":"Puntos",
            "blocks":"Bloqueos",
            "aces":"Directos",
            "receive.rating":"Nota de recepcion",
            "last.month.stats":"Mostrar estadisticas del ultimo mes",
            "scouting":"Scouting",
            "teams.analyzed":"Equipos analizados",
            "scout.new":"Nuevo análisis",
            "show.stats": "Mostrar datos",
            "useful.info":"Información relevante",
            "best.attack":"Mejor ataque",
            "worst.attack":"Peor ataque",
            "best.serve":"Mejor saque",
            "best.block":"Mejor bloqueo",
            "best.receiver":"Mejor rece",
            "worst.receiver":"Peor rece",
            "total.points":"Puntos totales",
            "best.rotation.stats":"Mejor rotación",
            "general.trends":"Tendencias generales",
            "initial.rotation":"Rotación inicial",
            "write.a.comment.max.55":"Escribe un comentario (max 55 car.)",
            "delete":"Borrar",
            "select":"Seleccionar",
            "done":"Listo",
            "over.pass.in.play":"Recepcion pasada en juego",
            "attempts":"Pases totales",
            "errors":"Errores",
            "earned":"Puntos ganados",
            "scouting.report":"Informe scouting",
            "team.report":"Informe de equipo",
            "report":"Informe",
            "date.range":"Rango de fechas",
            "number.matches":"Nº de partidos",
            "number.trainings":"Nº de entrenamientos",
            "match.report":"Informe de partido",
            "result":"Resultado",
            "totals":"Totales",
            "match.bests":"Mejores del partido",
            "mark":"Nota",
            "multi.match.report":"Informe multiples partidos",
            "matches.report":"Informe partidos",
            "league":"Liga",
            "non.league":"Fuera de liga",
            "tournament":"Torneo",
            "empty.tournaments":"No existen torneos",
            "no.tournament":"Sin torneo",
            "league.matches":"Partidos de liga",
            "tournaments":"Torneos",
            "tournament.delete":"Borrar torneo",
            "tournament.delete.description":"Los partidos asociados con el torneo no se eliminaran",
            "general":"General",
            "tournament.new":"Nuevo torneo",
            "tournament.setup":"Ajustes del torneo",
            "end.date":"Fecha de fin",
            "start.date":"Fecha de inicio",
            "location":"Lugar",
            "all.matches":"Todos los partidos",
            "birthday":"Fecha de nacimiento",
            "block.out":"Block out",
            "report.type":"Tipo de informe",
            "general.report":"Informe general",
            "full.report":"Informe completo",
            "tournament.stats":"Estadisticas del torneo",
            "players.rank.by.area":"Ranking de jugadores por area",
            "team":"Equipo",
            "add.from.team":"Añadir de otro equipo",
            "pick.team":"Elegir equipo",
            "pick.player":"Elegir jugador",
            "add.players":"Añadir jugadores",
            "serve.historical.stats":"Estadísticas históricas de saque",
            "receive.historical.stats":"Estadísticas históricas de recepción",
            "atk.historical.stats":"Estadísticas históricas de ataque",
            "height":"Altura",
            "weight":"Peso",
            "breadth":"Envergadura",
            "one.hand.reach":"Alcance una mano",
            "two.hand.reach":"Alcance dos manos",
            "attack.reach":"Alcance en ataque",
            "block.reach":"Alcance en bloqueo",
            "attack.jump":"Salto en ataque",
            "block.jump":"Salto en bloqueo",
            "player.data":"Datos del jugador",
            "player.measures":"Medidas del jugadors",
            "coming.soon":"Proximamente...",
            "gp" : "G-P",
            "help":"Ayuda",
            "general.explanation":"Se muestran 3 pantallas: capturar, estadisticas y registro de puntos. Cada una contiene información relevante para el partido.",
            "capture.explanation":"En esta pestaña es donde se capturan las acciones del partido.",
            "the.score": "Marcador",
            "the.score.explanation.1":"El marcador empieza 0-0. Un balón de voleibol aparecerá al lado de la puntuación del equipo al saque.",
            "the.score.explanation.2":"Si necesitas modificar el marcador o el equipo que saca, simplemente haz click en cualquiera de los botones del marcador y aparecerá una ventana para realizar los ajustes.",
            "current.rotation":"Rotación actual",
            "current.rotation.explanation.1":"La rotación será la que has especificado al iniciar el set y se actualizará automaticamente conforme introduzcas acciones.",
            "current.rotation.explanation.2":"Si necesitas ajustar la rotación, simplemente haz click en la rotación y aparecerá una ventana para realizar las modificaciones.",
            "capturing.stats":"Capturar estadísticas",
            "capturing.stats.explanation.1":"1. Clica en el botón del jugador que ha realizado la acción o si la acción ha sido realizada por el contrario clica en 'su jugador'.",
            "capturing.stats.explanation.2":"2. Clica en el botón de la acción que ha realizado el jugador.",
            "capturing.stats.explanation.3":"3. Clica en el botón 'Guardar' para añadir la acción.",
            "capturing.stats.explanation.4":"Puedes deshacer la última acción o limpiar los campos utilizando los botonez dedicados 'Limpiar' y 'Deshacer'.",
            "servers":"Sacadores",
            "servers.explanation.1":"Cuando sea el turno de tu equipo para sacar, un balón de voleibol aparecerá al lado del número del jugador que debe sacar.",
            "stats.explanation.1":"En esta ventana encontrarás un resumen de las estadisticas de tu equipo. La información se muestra en formato tabla y dividida por areas.",
            "stats.explanation.2":"Puedes encontrar mas informacion en la pestaña 'Estadisticas'.",
            "point.log.explanation":"En esta ventana se muestra un registro de las acciones que se han ido anotando durante el partido. Las columnas muestran la siguiente información:",
            "stage.explanation":"Indica si tu equipo saca o recibe.",
            "server.explanation":"Indica el nombre del jugador al saque o 'Su jugador' si saca el contrario.",
            "player.explanation":"Muestra el nombre del jugador que ha realizado la accion o 'Su jugador' si la acción es del contrario.",
            "action.type.explanation":"Indica si la accion es en juego, ganada, error o falta.",
            "action.explanation":"Muestra el nombre de la acción. Para algunas acciones aparecera el detalle entre corchetes.",
            "point.to.explanation":"El punto es para tu equipo ('Nosotros'), el rival ('Ellos') o para nadie si la acción es en juego.",
            "score.explanation":"Marcador final despues de la acción.",
            "actions.explanation":"Existen muchos botones de acción para capturar con el mayor detalle posible, pero puedes ser menos específico y capturar todas las acciones de la misma area con el mismo boton (Ex. Defensa, Free ball, y De quien era? capturadas con el botón 'Defensa').",
            "in.rally.actions":"Acciones en juego (gris)",
            "in.rally.explanation":"Estas acciones ocurren durante el juego u no terminan la jugada depues de capturarlas.",
            "in.rally.dig":"Pelota controlada después de una acción ofensiva del rival (Free ball no incluida).",
            "in.rally.free.ball.1":"Una free ball que no resulta en error pero que no se puede colocar en condiciones y está lejos de la línea de 3m.",
            "in.rally.free.ball.2":"Una free ball con altura suficiente que va cerca de la línea de 3m y la coloca el colocador.",
            "in.rally.free.ball.3":"Una free ball que es perfecta, cerca de la zona derecha del centro de la pista y que permite todas las opciones de ataque.",
            "in.rally.block":"Bloqueo de un ataque del rival en el que el baløn continúa en juego.",
            "in.rally.overpass":"Una recepción que va sobre la red al campo contrario. Si el rival puntúa en el primer toque, utiliza el botón de error de recepción.",
            "in.rally.receive.1":"Una recepción que no resulta en error pero que no se puede colocar en condiciones y está lejos de la línea de 3m.",
            "in.rally.receive.2":"Una recepción con altura suficiente que va cerca de la línea de 3m y la coloca el colocador.",
            "in.rally.receive.3":"Una recepción que es perfecta, cerca de la zona derecha del centro de la pista y que permite todas las opciones de ataque.",
            "in.rally.serve.1":"Un saque que permite una recepción de 3 (3-Recepcion).",
            "in.rally.serve.2":"Un saque que permite una recepción de 2 (2-Recepcion).",
            "in.rally.serve.3":"Un saque que permite una recepción de 1 (1-Recepcion).",
            "in.rally.hit":"Un ataque de tu jugador que continúa en juego.",
            "in.rally.downhit":"Un pase de mano baja de tu jugador que continúa en juego.",
            "earned.actions":"Acciones ganadas (verde)",
            "earned.actions.explanation":"Estas acciones son puntos ganados.",
            "earned.ace":"Un saque que resulta en un punto directo o en un error de recepción.",
            "earned.spike":"Un remate directo al suelo o que termina en un error de defensa del rival.",
            "earned.tip":"Un golpe suave, normalmente con la yema de los dedos, directo al suelo o que termina en un error de defensa del rival.",
            "earned.dump":"Golpe suave, normalmente del colocador cercano a la red, directo al suelo o que termina en un error de defensa del rival.",
            "earned.downhit":"Golpe o pase realizado desde el suelo, directo al suelo o que termina en un error de defensa del contrario.",
            "earned.block":"Cuando el baløn tocado por el bloqueo termina en punto.",
            "error.actions":"Acciones de error (amarillo)",
            "error.actions.explanation":"Acciones que terminan en punto para el rival.",
            "error.serve":"Cuando el saque se va fuera o a la red.",
            "error.attack":"Cuando la pelota se va fuera, a la red o es bloqueada.",
            "error.block":"Pelota tocada por el bloqueo que termina en punto para el equipo atacante.",
            "error.whose.ball":"Dos o mas jugadores que van a por el mismo balón y la jugada termina en un error o un balón no tocado.",
            "error.receive":"Cuando el saque no se controla o no se llega al balón.",
            "error.dig":"Error al intentar controlar un balón atacado por el equipo contrario (reamte, finta, finta del colocador)",
            "error.set":"Una colocación deficiente que termina en error.",
            "error.free.ball":"Error al intentar defender una free ball.",
            "fault.actions":"Acciones de falta (rojo)",
            "fault.actions.explanation":"Estas acciones son faltas tecnicas.",
            "fault.net":"Toque ilegal de la red por un jugador.",
            "fault.ball.handling":"Un jugador toca dos veces el balón o lo cambia de dirección acompañandolo (acompañamiento).",
            "fault.under":"Un jugador cruza la linea central con el pie completo por debajo de la red.",
            "fault.foot":"El sacador pisa o cruza la línea de saque durante la realización del mismo.",
            "fault.over.the.net":"Un jugador toca el balon en el campo rival por encima de la red (cuenta como error de bloqueo).",
            "fault.out.rotation":"Dos jugadores se superponen o el equipo no estaba en la rotacion correcta.",
            "fault.backrow.attack":"Un jugador zaguero realiza un ataque saltando desde dentro de la línea de 3m (cuenta como error de ataque).",
            "stats.explanation":"Encontramos diferentes pestañas que muestran la misma información aplicando filtros en función de si los datos son sobre el partido completo o un set concreto. La información se encuentra dividida en areas.",
            "stats.general.explanation":"Aqui se muestra información relevante de areas mezcladas.",
            "general.their.errors":"Numero de errores que ha realizado el rival sin la acción directa de tu equipo.",
            "general.serve.errors":"Numero de errores de saque de tu equipo.",
            "general.receive.rating":"Nota media de recepción de tu equipo (sobre 3).",
            "general.kill.percentage":"Porcentaje de ataques que terminan en punto para tu equipo. Si no estas anotando acciones en juego, es posible que este dato no muestre información real.",
            "general.match.bests":"*Si estas viendo las estadisticas generales del partido, aqui apareceran los mejores jugadores de cada area.",
            "stats.per.area":"Estadisticas por área",
            "area.explanation":"Aqui la información se muestra por jugador y dividida en las siguientes areas:",
            "area.attack.1":"Aqui se muestra el numero de ataques, los ataques puntuados, los errores y el porcentaje de puntos ganados.",
            "area.attack.2":"Si no ha capturado acciones en juego, es posible que la información del porcentaje de puntos ganados no sea real.",
            "area.block":"Aqui se muestra el total de bloqueos, los bloqueos ganados y los errores.",
            "area.dig":"Aqui se muestra el total de defensas y los errores.",
            "area.downhit":"Aqui se muestra el total de pases desde el suelo, los ganados y los errores. Esta vista es del general del equipo.",
            "area.fault":"Aqui se muestra el número de faltas de cada tipo.",
            "area.free":"Aqui se muestra el total de free ball, los errores, 1-free ball (-), 2-free ball (+), 3-free ball (++) y la nota media del jugador (sobre 3).",
            "area.receive":"Aqui se muestra el total de recepciones, los errores, 1-recepción (-), 2-recepción (+), 3-recepción (++) y la nota media del jugador (sobre 3).",
            "area.serve":"Aqui se muestra el total de saques, los errores, 1-saque (-), 2-saque (+), 3-saque (++), la nota media del jugador (sobre 3) y el numero de puntos ganados por el equipo mientras cada jugador estaba al saque.",
            "area.set":"Aqui se muestran los errores de colocación.",
            "1.receive":"1-Recepcion",
            "2.receive":"2-Recepcion",
            "3.receive":"3-Recepcion",
            "1.serve":"1-Saque",
            "2.serve":"2-Saque",
            "3.serve":"3-Saque",
            "offline":"Sin conexión a internet",
            "stats.rotation.explanation":"Aqui aparecen las estadisticas de cada rotacion. Se muestra la rotacion inicial, pero los datos son de todas las iteraciones de la rotacion",
            "side.out.explanation":"Los puntos de sideout, son los que tu equipo ha conseguido con la salida de recepcion (K1). Es decir, el punto que hace a tu equipo recuperar el saque.",
            "break.point.explanation":"Los puntos de break point son los que tu equipo ha conseguido mientras tiene el saque (K2).",
            "user.area":"Zona de usuario",
            "log.out":"Cerrar sesión",
            "login":"Entrar",
            "sign.up":"Crear cuenta",
            "verify.password":"Repite contraseña",
            "password":"Contraseña",
            "username":"Nombre de usuario",
            "email":"Email",
            "backup.error":"Error haciendo copia de seguridad",
            "backup.saved":"Copia de seguridad guardada",
            "data.imported":"Copia de seguridad restablecida",
            "error.importing":"Error restableciendo copia de seguridad",
            "show.game.graph":"Mostrar curva de registro",
            "position":"Posicion",
            "setter":"Colocador",
            "opposite":"Opuesto",
            "outside":"Receptor",
            "midBlock":"Central",
            "libero":"Libero",
            "universal":"Universal",
            "game.mode":"Sistema de juego",
            "teams":"Equipos",
            "same.position":"Misma posicion",
            "other":"Otra posicion",
            "player.report":"Informe de jugador",
            "match.played":"Partidos jugados",
            "set.played":"Sets jugados",
            "ace.short":"Directos",
            "generate":"Generar",
            "pick.date.range":"Rango de fechas",
            "add.feedback":"Añadir comentarios",
            "customize.report":"Personalizar informe",
            "points":"Puntos",
            "not.enough.setters":"No hay suficientes colocadores o estan mal colocados",
            "cant.change":"No se puede realizar el cambio",
            "n.changes":"Cambios",
            "match.compare":"Comparación con anterior",
            "error.tree":"Resumen errores",
            "actual":"Actual",
            "previous":"Anterior",
            "serve.detail":"Detalle de saques",
            "receive.detail":"Detalle de recepciones",
            "attack.detail":"Detalle de ataques",
            "full.stats":"Estadísticas completas",
            "stats.by.type":"Tipo de estadísticas",
            "fill.stats":"Rellenar estadísticas",
            "last.point":"Punto anterior",
            "next.point":"Punto actual",
            "last.action":"Acción anterior",
            "next.action":"Acción siguiente",
            "in.game.actions":"Acciones en juego",
            "no.action":"No hay acciones registradas",
            "no.next.point":"Utiliza el metodo normal de captura"
        ]
    ]
}
